# Generated by Django 5.1.1 on 2024-10-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepblueapp', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='cleared_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
